(define (problem collect_wood_make_stone_pickaxe_problem)
  (:domain collect_wood_domain)
  (:init
    (= (inv_wood) 0)
    (= (inv_stone) 0)
    (= (inv_wood_pickaxe) 0)
    (= (inv_stone_pickaxe) 0)
    (= (inv_wood_sword) 0)
    (= (ach_collect_wood) 0)
    (= (ach_collect_stone) 0)
    (= (ach_place_table) 0)
    (= (ach_place_stone) 0)
    (= (ach_make_wood_pickaxe) 0)
    (= (ach_make_stone_pickaxe) 0)
    (= (ach_make_wood_sword) 0)
  )
  (:goal (>= (ach_make_stone_pickaxe) 1))
)