(define (domain collect_wood_domain)
  (:requirements :strips :typing :fluents)
  (:types actor resource achievement)
  (:constants ach_collect_wood ach_collect_stone ach_place_table ach_place_stone ach_make_wood_pickaxe ach_make_wood_sword - achievement)
  (:predicates
    (adjacent_to ?who - actor ?target - resource)
    (tree ?target - resource)
    (stone ?target - resource)
    (achieved ?result - achievement)
  )
  (:functions
    (inv_wood)
    (inv_stone)
    (inv_wood_pickaxe)
    (inv_wood_sword)
  )
  (:action collect_wood
    :parameters (?who - actor ?target - resource)
    :precondition (and (adjacent_to ?who ?target) (tree ?target))
    :effect (and (increase (inv_wood) 1) (achieved ach_collect_wood))
  )
  (:action place_table
    :parameters (?who - actor)
    :precondition (and (>= (inv_wood) 2))
    :effect (and (decrease (inv_wood) 2) (achieved ach_place_table))
  )
  (:action make_wood_pickaxe
    :parameters (?who - actor)
    :precondition (and (achieved ach_place_table) (>= (inv_wood) 1))
    :effect (and (decrease (inv_wood) 1) (increase (inv_wood_pickaxe) 1) (achieved ach_make_wood_pickaxe))
  )
  (:action make_wood_sword
    :parameters (?who - actor)
    :precondition (and (achieved ach_place_table) (>= (inv_wood) 1))
    :effect (and (decrease (inv_wood) 1) (increase (inv_wood_sword) 1) (achieved ach_make_wood_sword))
  )
  (:action collect_stone
    :parameters (?who - actor ?target - resource)
    :precondition (and (adjacent_to ?who ?target) (stone ?target) (>= (inv_wood_pickaxe) 1))
    :effect (and (increase (inv_stone) 1) (achieved ach_collect_stone))
  )
  (:action place_stone
    :parameters (?who - actor)
    :precondition (and (>= (inv_stone) 1))
    :effect (and (decrease (inv_stone) 1) (achieved ach_place_stone))
  )
)