(define (problem wood_collection_problem)
  (:domain wood_collection)
  (:init
    (= (inv_wood) 0)
    (= (inv_stone) 0)
    (= (inv_wood_pickaxe) 0)
    (= (inv_stone_pickaxe) 0)
    (= (inv_wood_sword) 0)
    (= (inv_stone_sword) 0)
  )
  (:goal (ach_make_stone_sword))
)