(define (domain collect_wood_domain)
  (:requirements :strips :typing :negative-preconditions)
  (:types actor resource status - object collectstatus placestatus - status)
  (:predicates
    (adjacent_to ?who - actor ?target - resource)
    (harvestable_wood ?target - resource)
    (wood_at_least_one ?who - actor)
    (wood_at_least_two ?who - actor)
    (placement_ready ?who - actor)
    (achieved ?flag - status)
  )
  (:action approach_wood
    :parameters (?who - actor ?target - resource)
    :precondition (harvestable_wood ?target)
    :effect (adjacent_to ?who ?target)
  )
  (:action collect_wood
    :parameters (?who - actor ?target - resource ?flag - collectstatus)
    :precondition (and (adjacent_to ?who ?target) (harvestable_wood ?target) (not (wood_at_least_one ?who)))
    :effect (and (wood_at_least_one ?who) (achieved ?flag) (not (harvestable_wood ?target)) (not (adjacent_to ?who ?target)))
  )
  (:action collect_more_wood
    :parameters (?who - actor ?target - resource ?flag - collectstatus)
    :precondition (and (adjacent_to ?who ?target) (harvestable_wood ?target) (wood_at_least_one ?who) (not (wood_at_least_two ?who)))
    :effect (and (wood_at_least_two ?who) (achieved ?flag) (not (harvestable_wood ?target)) (not (adjacent_to ?who ?target)))
  )
  (:action prepare_table_placement
    :parameters (?who - actor)
    :precondition (and)
    :effect (placement_ready ?who)
  )
  (:action place_table
    :parameters (?who - actor ?flag - placestatus)
    :precondition (and (wood_at_least_two ?who) (placement_ready ?who))
    :effect (and (achieved ?flag) (not (wood_at_least_two ?who)) (not (wood_at_least_one ?who)) (not (placement_ready ?who)))
  )
)